# Understanding Pandas Series and DataFrames - Lab

## Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

## Let's get started!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

197625

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

## Rename all the columns to lower case

In [3]:
#Your code here
df.rename(str.lower, axis='columns')

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941
...,...,...,...,...,...,...,...,...,...,...,...
197595,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348
197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348
197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348
197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348
197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348
197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348
197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348
197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348
197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348
197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348
197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348
197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348
197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348
197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348
197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348
197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348
197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348
197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348
197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348
197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348
197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348
197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348
197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348
197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348
197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348
197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348
197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348
197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348
197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348
197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348

## Change the Index to be the Line Names

In [4]:
#Your code here
df.set_index(df['LINENAME'])

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
LINENAME,,,,,,,,,,,
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941
...,...,...,...,...,...,...,...,...,...,...,...
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348

## Change the index back

In [5]:
# Your code here
df.reset_index()
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order
*Hint: According to the [data dictionary](http://web.mta.info/developers/resources/nyct/turnstile/ts_Field_Description.txt), LINENAME represents all train lines that can be boarded at a given station. Normally lines are represented by one character. For example, LINENAME 456NQR represents trains 4, 5, 6, N, Q, and R.*

In [6]:
# Your code here
num_lines = []
for line in df['LINENAME']:
    num_lines.append(len(line))

df['Num_Lines'] = num_lines
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Num_Lines
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184,7
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229,7
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314,7
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384,7
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425,7
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460,7
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461,7
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483,7
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524,7
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587,7
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631,7
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656,7
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658,7
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736,7
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965,7
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025,7
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091,7
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121,7
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126,7
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216,7
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402,7
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425,7
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478,7
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508,7
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512,7
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600,7
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838,7
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896,7
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941,7
...,...,...,...,...,...,...,...,...,...,...,...,...
197595,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348,1
197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348,1
197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348,1
197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348,1
197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348,1
197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348,1
197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348,1
197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348,1
197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348,1
197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348,1
197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348,1
197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348,1
197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348,1
197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348,1
197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348,1
197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348,1
197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348,1
197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348,1
197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348,1
197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348,1
197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348,1
197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348,1
197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348,1
197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348,1
197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348,1
197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348,1
197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348,1
197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348,1
197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348,1
197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348,1

## Write a function to clean a column name

In [7]:
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               ',
       'Num_Lines'],
      dtype='object')

In [8]:
def clean(col_name):
    cleaned = col_name.title()
    return cleaned

In [9]:
# This is a list comprehension. It applies your clean function to every item in the list.
# We then reassign that to df.columns
# You shouldn't have to change anything here.
# Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [10]:
# Checking the output, we can see the results.
df.head()

,C/A,Unit,Scp,Station,Linename,Division,Date,Time,Desc,Entries,Exits,Num_Lines
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184,7
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229,7
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314,7
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384,7

## Group the Data by Day of Week and Plot the Sum of The Numeric Columns

In [11]:
from datetime import datetime
import numpy as np

In [13]:
# Your code here
temp = pd.to_datetime(df['Date'])
#temp2 = pd.datetime.strptime(df['Date'])

In [14]:
temp2 = []
for date_listing in temp:
    temp2.append(datetime.date(date_listing).weekday())

In [15]:
df['int_day_of_week'] = temp2

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197625 entries, 0 to 197624
Data columns (total 13 columns):
C/A                                                                     197625 non-null object
Unit                                                                    197625 non-null object
Scp                                                                     197625 non-null object
Station                                                                 197625 non-null object
Linename                                                                197625 non-null object
Division                                                                197625 non-null object
Date                                                                    197625 non-null object
Time                                                                    197625 non-null object
Desc                                                                    197625 non-null object
Entries                                                                 197625 non-null int64
Exits                                                                   197625 non-null int64
Num_Lines                                                               197625 non-null int64
int_day_of_week                                                         197625 non-null int64
dtypes: int64(4), object(9)
memory usage: 19.6+ MB

In [17]:
df['int_day_of_week']

0         5
1         5
2         5
3         5
4         5
5         5
6         6
7         6
8         6
9         6
10        6
11        6
12        0
13        0
14        0
15        0
16        0
17        0
18        1
19        1
20        1
21        1
22        1
23        1
24        2
25        2
26        2
27        2
28        2
29        2
         ..
197595    0
197596    0
197597    0
197598    0
197599    0
197600    0
197601    1
197602    1
197603    1
197604    1
197605    1
197606    1
197607    2
197608    2
197609    2
197610    2
197611    2
197612    2
197613    3
197614    3
197615    3
197616    3
197617    3
197618    3
197619    4
197620    4
197621    4
197622    4
197623    4
197624    4
Name: int_day_of_week, Length: 197625, dtype: int64

In [19]:
df['is_weekday'] = np.isin(df['int_day_of_week'], [0,1,2,3,4])

## Group the Data by Weekend/Weekday and Plot the Sum of the Numeric Columns

In [20]:
df['int_day_of_week']

0         5
1         5
2         5
3         5
4         5
5         5
6         6
7         6
8         6
9         6
10        6
11        6
12        0
13        0
14        0
15        0
16        0
17        0
18        1
19        1
20        1
21        1
22        1
23        1
24        2
25        2
26        2
27        2
28        2
29        2
         ..
197595    0
197596    0
197597    0
197598    0
197599    0
197600    0
197601    1
197602    1
197603    1
197604    1
197605    1
197606    1
197607    2
197608    2
197609    2
197610    2
197611    2
197612    2
197613    3
197614    3
197615    3
197616    3
197617    3
197618    3
197619    4
197620    4
197621    4
197622    4
197623    4
197624    4
Name: int_day_of_week, Length: 197625, dtype: int64

In [26]:
#Your code here
by_weekday = df.groupby(['int_day_of_week'], as_index=True)
by_weekday[:10]

TypeError: unhashable type: 'slice'

## Analysis Question: 

What is misleading about the day of week and weekend/weekday charts you just plotted?

In [ ]:
# Your answer here

## Drop a couple of columns

In [ ]:
# Your code here

## Summary

Great! You practiced your data cleanup-skills using Pandas.